# Generated by Django 4.2.16 on 2025-05-26 01:31

from django.db import migrations
import karrio.server.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0061_alter_surcharge_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surcharge",
            name="carriers",
            field=karrio.server.core.fields.MultiChoiceField(
                blank=True,
                choices=[
                    ("allied_express", "allied_express"),
                    ("allied_express_local", "allied_express_local"),
                    ("amazon_shipping", "amazon_shipping"),
                    ("aramex", "aramex"),
                    ("asendia_us", "asendia_us"),
                    ("australiapost", "australiapost"),
                    ("boxknight", "boxknight"),
                    ("bpost", "bpost"),
                    ("canadapost", "canadapost"),
                    ("canpar", "canpar"),
                    ("chronopost", "chronopost"),
                    ("colissimo", "colissimo"),
                    ("dhl_express", "dhl_express"),
                    ("dhl_parcel_de", "dhl_parcel_de"),
                    ("dhl_poland", "dhl_poland"),
                    ("dhl_universal", "dhl_universal"),
                    ("dicom", "dicom"),
                    ("dpd", "dpd"),
                    ("dpdhl", "dpdhl"),
                    ("easypost", "easypost"),
                    ("easyship", "easyship"),
                    ("eshipper", "eshipper"),
                    ("fedex", "fedex"),
                    ("fedex_ws", "fedex_ws"),
                    ("freightcom", "freightcom"),
                    ("generic", "generic"),
                    ("geodis", "geodis"),
                    ("hay_post", "hay_post"),
                    ("laposte", "laposte"),
                    ("locate2u", "locate2u"),
                    ("logistic_io", "logistic_io"),
                    ("nationex", "nationex"),
                    ("purolator", "purolator"),
                    ("roadie", "roadie"),
                    ("royalmail", "royalmail"),
                    ("sapient", "sapient"),
                    ("seko", "seko"),
                    ("sendle", "sendle"),
                    ("tge", "tge"),
                    ("tnt", "tnt"),
                    ("ups", "ups"),
                    ("usps", "usps"),
                    ("usps_international", "usps_international"),
                    ("usps_wt", "usps_wt"),
                    ("usps_wt_international", "usps_wt_international"),
                    ("zoom2u", "zoom2u"),
                ],
                help_text="\n        The list of carriers you want to apply the surcharge to.\n        <br/>\n        Note that by default, the surcharge is applied to all carriers\n        ",
                null=True,
            ),
        ),
    ]
