# Generated by Django 5.2.4 on 2025-07-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0062_alter_surcharge_carriers"),
        ("pricing", "0064_alter_surcharge_carriers_alter_surcharge_services"),
    ]

    operations = []
