services:
  karrio.api:
    container_name: karrio.api
    image: ilhamakbarki/karrio:staging_beta
    restart: unless-stopped
    ports:
      - ${KARRIO_HTTP_PORT}:${KARRIO_HTTP_PORT}
    environment:
      DEBUG_MODE: "True"
      DETACHED_WORKER: "True"
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      KARRIO_HTTP_PORT: ${KARRIO_HTTP_PORT}
      ENABLE_ALL_PLUGINS_BY_DEFAULT: "True"
    healthcheck:
      test: curl --fail http://api:5002/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 5
      start_period: 60s

  karrio.worker:
    container_name: karrio.worker
    image: ilhamakbarki/karrio:staging_beta
    restart: unless-stopped
    depends_on:
      - api
    environment:
      DEBUG_MODE: "True"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ENABLE_ALL_PLUGINS_BY_DEFAULT: "True"
    command: "/bin/bash ./worker"

  karrio.dashboard:
    container_name: karrio.dashboard
    image: ilhamakbarki/karrio.dashboard:staging_beta
    restart: unless-stopped
    ports:
      - ${DASHBOARD_PORT}:3000/tcp
    depends_on:
      api:
        condition: service_healthy
        restart: true
    environment:
      AUTH_TRUST_HOST: true
      NEXTAUTH_SECRET: ${SECRET_KEY}
      NEXT_PUBLIC_DASHBOARD_URL: ${DASHBOARD_URL}
      NEXT_PUBLIC_KARRIO_PUBLIC_URL: ${KARRIO_PUBLIC_URL}
      KARRIO_URL: http://api:${KARRIO_HTTP_PORT:-5002}

  maildev:
    container_name: karrio.mail
    image: maildev/maildev
    restart: on-failure
    ports:
      - "1080:1080"
      - "1025:1025"

  # Comment out everything below this point if you are using an external database and redis instance.
  # karrio.db:
  #   container_name: karrio.db
  #   image: postgres:15.13-alpine3.22
  #   restart: unless-stopped
  #   ports:
  #     - ${DATABASE_PORT}:5432
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     PGDATA: /var/lib/postgresql/data/karrio
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # karrio.redis:
  #   container_name: karrio.redis
  #   image: redis:7.2.10-alpine
  #   restart: unless-stopped
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis-data:/data

# volumes:
#   postgres-data:
#   redis-data:
